version: "3"
volumes:
  node_modules:
services:
  frontend:
    container_name: "zizityp"
    volumes:
      - .:/frontend
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/frontend'
      - 'node_modules:/frontend/node_modules'
    ports:
      - 8080:8080
  backend:
    container_name: 'tatakimaru'
    volumes:
      - './tatakimaru:/backend'
    tty: true
    build:
      context: ./tatakimaru
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000