version: "3"
services:
  tatakimaru:
    container_name: "tatakimaru"
    volumes:
      - ./:/backend
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000